### ISSUE TITLE
Unique taxa OTU table

### ISSUE THREAD

**Issue by Madegwa** [schuyler-smith/phylosmith#11]
Hello,
Thank you for the awesome package i just began to use it for 16S analysis. 
I have a question in regards to "unique_taxa" command
Instead of obtaining only the list of unique taxa, is it possible to extract the OTU table of the unique taxa as well? 
I want to do some analysis on the unique taxa OTU table. 
Any assistance will be highly appreciated

Thank you

**Comment by schuyler-smith** [comment]
Hey, thank you for the kind words. I really hope that you find the package useful and it helps with your analysis. I keep missing these notification and say I will fix my github to push them to me but I never do it, so I will fix it today, sorry for the delayed response.

I do not currently have a quick-and-easy function to do what you want, but we can work alongside phyloseq to get it done!

using the soil_column dataset that I send with phylosmith and use in my examples we can subset like so:
```
unique_soil_taxa <- unique_taxa(soil_column, c('Matrix', 'Treatment'))
```
we want only the taxa from the 'Soil Unamended' samples:
```
unique_soil_taxa <- unique_soil_taxa[[2]]
```
when dealing with a list object [[ extracts and enlists the elements, it would be equivalent to unlist(unique_soil_taxa[2])

then we can use phyloseq::subset_taxa() with phyloseq::taxa_names()
```
subset_taxa(soil_column, taxa_names(soil_column) %in% unique_soil_taxa)
```

**Comment by Madegwa** [comment]
Yeah it was exactly what i was looking for, thank you!!
