### ISSUE TITLE
Missing description in every treatment arguments (webpage)

### ISSUE THREAD

**Issue by dikiprawisuda** [schuyler-smith/phylosmith#12]
Hi,
I found a missing word, it seems, in conglomerate_samples arguments of treatment description. It says:
Column name as a string or numeric in the . This can be a vector of multiple columns and they will be combined into a new column.

Which column name are these referring to?
Thank you.

Best,

**Comment by schuyler-smith** [comment]
Oh wow! This happens repeatedly, I must have tried to correct it with a regex and messed it up. Thank you!
