### ISSUE TITLE
custom labels for treatments / facets for graphs

### ISSUE THREAD

**Issue by ctekellogg** [schuyler-smith/phylosmith#14]
Hi! I am loving the graphing functions you have as part of `phylosmith` and your entire package in general. Thank you! Is there a way to make custom labels for the subplots / facets, rather than the shorthand I have used for treatments in my phyloseq object?

Thank you!
Colleen

**Comment by schuyler-smith** [comment]
Hey Colleen, Thank you so much for the kind words. I am very glad that you this useful! Sorry that I didn't get back you sooner. 

You can do this. You would need to do it through a ggplot call though. Off-hand I think I recall it not being trivial to do for faceted plots though. The easiest thing would definitely be to change it in the phyloseq object, or even the original data loaded into the object.

**Comment by schuyler-smith** [comment]
I just pushed an update to add this ability to the graph functions, or most of them at least. You should be able to use the arguments "treatment_labels", "sample_labels", "classification_labels". I haven't tested each of them yet, but I didn't get any errors from my example tests.. so hopefully it works! if you try it out, let me know if this helps!

**Comment by ctekellogg** [comment]
Hi! Thanks so much for doing this. I am trying to use this for your phylogeny_profiles function. For some reason it doesn't seem to work for me. Not sure how to provide a reproducible example here, but at the least I can give an example of the vector I am trying to us:

i've tried employing something like: `sample_data(fw18S_r2R)$Day_Type2` where `fw18S_r2R` is my phyloseq object and I just want to name the samples by a different column of the sample data. That didn't work, so then I made a vector of the sample thing 'by hand', for example: 

`short<-c("11 Mid","11 Mid","11 Mid", "11 Mid","12 Night","12 Night","12 Night","13 Morning", "13 Morning", "13 Morning", "13 Morning","13 Mid","13 Mid","13 Mid","13 Mid","13 Night","13 Night","13 Night","13 Night","15 Morning","15 Morning","15 Morning","15 Morning","15 Mid","15 Mid", "15 Mid","15 Mid", "15 Night","15 Night","15 Night","15 Night","18 Morning","18 Morning", "18 Morning", "18 Morning", "18 Mid", "18 Mid", "18 Mid","18 Mid",  "18 Night","18 Night","18 Night","18 Night")`

and then when I run the following: `phylogeny_profile(fw18S_r2R, "Rank2_15", treatment = "Depth", relative_abundance = FALSE, colors = mycolorsPaired15, sample_labels = short)`

 I get the following error:

`Error in phylogeny_profile(fw18S_r2R, "Rank2_15", treatment = "Depth",  : 
  unused argument (sample_labels = short)`

What was the structure of your vector such that it worked?

I am happy your plotting function maintains the order of my samples because when I tried to you `plot_bar` in phyloseq it kept reordering the samples in alphabetical order and try as I may I cannot get it to keep my sample order when plotting (even though I've figured out how to hypothetically rename the x axis labels using the `scale_x_discrete(labels = )` if I cannot get it to maintain the correct sample order then that doesn't help me either. 

Thank you!
Colleen

**Comment by schuyler-smith** [comment]
It should work as you have it. Just to make sure, did you reinstall the package? That error comes when the argument is not used in the function, which should not be the case with the most recent version.

If you have reinstalled it.. then I will need to delve into it a bit.
