### ISSUE TITLE
Loading Phylosmith

### ISSUE THREAD

**Issue by vee3capp** [schuyler-smith/phylosmith#17]
I had previously installed phylosmith, but it is not recognizing the library when I am trying to load it. I have tried a couple of ways of installment too. I just keep getting this: 
Error in library(phylosmith) : there is no package called ‘phylosmith'

**Comment by schuyler-smith** [comment]
Hey! Sorry for the late reply. This could be a number of things. Have you recently upgraded your version of R? If so, then it probably started a new package directory and you need to reinstall phylosmith again, or migrate it from the old folder.

I am not sure what the package 'cli' is. It is not one that phylosmith directly uses. It may be required by one of its dependencies. Have you updated all your other packages? I'd try devtools::update_packages() and make sure that everything is as current as can be. If that doesn't solve the problem, just try to install 'cli' again with install.packages('cli'). As a last resort, you can try removing your previous installation of phylosmith manually and reinstalling it. If you are on a windows machine, it's usually under documents/R/win-library/.. 

Let me know if any of these work. If not, we can try some other things!

**Comment by vee3capp** [comment]
After uninstalling and reinstalling cli and then trying to install phylosmith it worked! Thank you

**Comment by schuyler-smith** [comment]
Great! I am glad it worked! Feel free to reach out if any other issues occur!
