### ISSUE TITLE
Line Colors

### ISSUE THREAD

**Issue by vee3capp** [schuyler-smith/phylosmith#18]
Hello 

I am using the abundance_lines function, and I was wondering if there any way to denote specific taxa as specific colors without using a palate or something?

**Comment by schuyler-smith** [comment]
The short answer is no. The long answer is yes. The function is not setup to be able map specific taxa to a color, but that doesn't mean we can't do it on our own!

Do you want to specify just a few specific taxa and leave all the others as what they are, or assign specific colors to all the taxa in your dataset?

**Comment by vee3capp** [comment]
![Screenshot 2022-04-06 194255](https://user-images.githubusercontent.com/78462291/162091961-2613c23b-9b9e-4875-b306-1f237b9a81a1.png)

I have these different graphs with only 5 families. Some of the families overlap. I just want it so all the families are the same colors throughout the graph. 

Here is my code to made a graph 

#Subset top 5 changing taxa (found from excel file)
top.aa.5<-subset_taxa(m.aa, family=="Planococcaceae"| family=="Moraxellaceae"| family=="Moraxellaceae"| family=="Lactobacillaceae"| family=="Veillonellaceae"| family=="[Tissierellaceae]")

#Plot
aa.line<-abundance_lines (top.aa.5, classification = 'family', treatment = c('decomp.stage'), relative_abundance = TRUE, points = TRUE,) + labs (title = "Prevelant Changing Taxa: Abdominal Area", x="Stage of Decomposition", y= "Relative Abundance",color="Family"); aa.line

**Comment by schuyler-smith** [comment]
Sure! We can do this.

First thing we want to do is create a sort of map for the colors.

```
taxa_of_interest <- c("Planococcaceae", "Moraxellaceae", "Lactobacillaceae", "Veillonellaceae", "[Tissierellaceae]")
taxa_colors <- phylosmith:::create_palette(length(taxa_of_interest))
```

If you want to keep using the default colors, otherwise you can pick any 5 colors you prefer!

Once the aa.line object is created, we can access the order of the taxa via `unique(aa.line$data$OTU)` . Then with these three things, we can `match` the order to our "map" and then redefine the color scale for the ggplot object.

```
aa.line + ggplot2::scale_color_manual(values = taxa_colors[match(unique(aa.line$data$OTU), taxa_of_interest, FALSE)])
```

This should do what you want (though I didn't test it out). If it doesn't, let me know.

**Comment by vee3capp** [comment]
Hi I would think that would work; but I am still getting the same colors. Do I need to change something for the color input too?

**Comment by schuyler-smith** [comment]
When you say the same colors, do you mean that the palette is the same, or the colors are not mapped to the taxa as we wanted?

**Comment by vee3capp** [comment]
I think right now I am just using the default color choices using my original code.

#Subset top 5 changing taxa (found from excel file)
top.aa.5<-subset_taxa(m.aa, family=="Planococcaceae"| family=="Moraxellaceae"| family=="Moraxellaceae"| family=="Lactobacillaceae"| family=="Veillonellaceae"| family=="[Tissierellaceae]")

#Plot
aa.line<-abundance_lines (top.aa.5, classification = 'family', treatment = c('decomp.stage'), relative_abundance = TRUE, points = TRUE,) + labs (title = "Prevelant Changing Taxa: Abdominal Area", x="Stage of Decomposition", y= "Relative Abundance",color="Family"); aa.line

This code (with variation for each sampling location) produces the graphs I previously posted. 

When I tried doing the code you gave, the colors are not mapped out to the taxa I wanted. I think I am missing a piece because currently, I have no specific code setting the colors; I am just using the default.  

I hope that makes sense.

**Comment by schuyler-smith** [comment]
The code I gave you should work to map the colors to the taxa, run after the code you posted. Here is a working example using two datasets in the package:

```
taxa_of_interest <- c("Actinobacteriota", "Cyanobacteria", "Firmicutes", "Proteobacteria")

a <- phylosmith::conglomerate_taxa(phylosmith::ia_lakes, "Phylum")
a <- phylosmith::taxa_extract(a, taxa_of_interest)
a <- phylosmith::abundance_lines(a, treatment = 'Location')

b <- phylosmith::conglomerate_taxa(phylosmith::soil_column, "Phylum")
b <- phylosmith::taxa_extract(b, taxa_of_interest)
taxa_names(b)[1] <- "Cyanobacteria"
b <- phylosmith::abundance_lines(b, treatment = 'Day')

color_map <- data.frame(taxa = taxa_of_interest,
                        colors = phylosmith:::create_palette(length(taxa_of_interest)))
a_colors <- color_map$colors[match(unique(a$data$OTU), color_map$taxa, FALSE)]
b_colors <- color_map$colors[match(unique(b$data$OTU), color_map$taxa, FALSE)]

a
a + ggplot2::scale_color_manual(values = a_colors)
b
b + ggplot2::scale_color_manual(values = b_colors)
```

Note the color changes from the originals (`a` and `b`) to the ones where I change the `+ scale_color_manual()`, and the consistency with the taxa.
