### ISSUE TITLE
Changing colour of NA values in abundance_heatmap

### ISSUE THREAD

**Issue by elayton13** [schuyler-smith/phylosmith#19]
Hi,

Firstly I love this package, its so useful and easy to use so thank you! I just have one small little niggly problem I'm struggling to find a solution for as they all seem to depend on the function that you use for making the heatmap in the first place, or the standalone use of Rcolorbrewer. When using non-default colours to plot relative abundance e.g.  

abundance_heatmap(run1_1percent, classification = 'Species', treatment = 'condition', subset = NULL, transformation = 'relative_abundance', colors = 'YlOrRd')

Is there a way to change the colour of the 0 values so that they are not grey, and outside of the color scale?

Thank you!
Emma

**Comment by schuyler-smith** [comment]
Thanks for the kind words! It means a lot to hear that you find the package useful!

I hadn't included that option, but I certainly can add it. The "easiest" way to change it after the plot is made, would be to assign the abundance plot to a variable, and then edit the object like so: 

```
my_heatmap <- abundance_heatmap(run1_1percent, classification = 'Species', treatment = 'condition', subset = NULL, transformation = 'relative_abundance', colors = 'YlOrRd')
my_heatmap $scales$scales[[2]]$na.value <- "white"
```

Where "white" is whatever color you'd like the 0 values to be. I set 0 values to be `NA`, which I suppose opens a philosophical debate of whether 0 and `NA` are synonymous in these types of datasets, and in some cases it definitely does matter..

Anyways, to set the `NA` values to be the left-tail of your chosen color palette you could do

```
my_heatmap $scales$scales[[2]]$na.value <- RColorBrewer::brewer.pal(RColorBrewer::brewer.pal.info["YlOrRd", "maxcolors"], "YlOrRd")[1]
```

Let me know if that does what you want! And feel free to reach out with any other questions that will help you with your analyses!
