### ISSUE TITLE
Error of co_occurrence_network()#

### ISSUE THREAD

**Issue by Yuxia88** [schuyler-smith/phylosmith#22]
Hi Schuyler,
Thanks for providing such a  convenient package for microbiome analysis. It is a great resource.
I am going to creat a co-occurrence network for my data. But there are errors occured when i attempted to run the example code of co_occurrence_network.  And i do not know how to solve it. The detais are following:
`co_occurrence_network(soil_column, treatment = c('Matrix', 'Treatment'), subset = 'Soil Amended', co_occurrence_table = NULL, classification = 'Phylum')`
   Error in if (is.null(classification) & node_colors == "default") { :
     the condition has length > 1
looking forward your reply, 
Thanks,

**Comment by schuyler-smith** [comment]
Thank you so much for your appreciation. Also, thanks so much for pointing out this bug for me. I think I figured out the sources of errors that were causing this. I pushed an update, please try it out and let me know how it goes!

Also, sorry for the delay. I was traveling this week, and just saw this today!

**Comment by Yuxia88** [comment]
Thank you so much for your reply,  this #co_occurrence_network function could work well and draw pictures normally.
