### ISSUE TITLE
co_occurrence networking 

### ISSUE THREAD

**Issue by PMilletich** [schuyler-smith/phylosmith#23]
I'm working on using your co_occurrence_network, and I'm having trouble understanding how to implement the "co_occurrence_table" parameters. 

I thought if I made a co-occurrence() table with rho = 0.8 and p = 0.05 which is listed as the defaults, and gave that to co_occurrence_network(), it would give me the same results as if I just ran co_occurrence_network() with co_occurrence_table = NULL. I think there might be a parameter that I'm missing in one or the other, so I'm sorry if this is a blatant answer 

`library(phylosmith)
library(ggplot2)
library(ggpubr)

data(GlobalPatterns)
#Load sample data and glom to Family to reduce processing time 
Sample_data = data.frame(sample_data(GlobalPatterns)) #[ 19216 taxa and 26 samples ]
phyloseq_obj = tax_glom(GlobalPatterns, "Family") #[ 341 taxa and 26 samples ]

No_table = co_occurrence_network(phyloseq_obj, treatment = NULL, subset = NULL, 
                                 co_occurrence_table = NULL, 
                                 classification = "Family", 
                                 node_colors = 'default', cluster = FALSE, 
                                 cluster_colors = 'default', buffer = 0.5)

Rho_0.8 = co_occurrence(phyloseq_obj, rho = 0.8, p = 0.05, cores = 0)

With_table = co_occurrence_network(phyloseq_obj, treatment = NULL, subset = NULL, 
                                 co_occurrence_table = Rho_0.8, 
                                 classification = "Family", 
                                 node_colors = 'default', cluster = FALSE, 
                                 cluster_colors = 'default', buffer = 0.5)

ggarrange(No_table, With_table, legend = "none", ncol = 2,
          labels = c("No Table", "Rho = 0.8"))`

**Comment by schuyler-smith** [comment]
Hi. Thank you so much for the reproducible example, that helped me a lot!

So.. your understanding of how it should work is correct, they should be the same. The problem is that I did not write the documentation complete enough. When `co_occurrence_table = NULL` the `co_occurrence_network()` (or rather the `network_layout_ps()`) creates a table equivalent to `co_occurrence(phyloseq_obj, rho = 0.6, p = 0.05)`. Probably I should mention that somewhere.. it's kind of important..

As a bonus, if you want to create two networks using identical layouts, use `network_layout_ps()` to build your layout first. Like this in the fantastic example you provided:
```
library(phyloseq)
library(phylosmith)
library(ggplot2)
library(ggpubr)

data(GlobalPatterns)
#Load sample data and glom to Family to reduce processing time
Sample_data = data.frame(sample_data(GlobalPatterns)) #[ 19216 taxa and 26 samples ]
phyloseq_obj = tax_glom(GlobalPatterns, "Family") #[ 341 taxa and 26 samples ]

my_layout <- network_layout_ps(phyloseq_obj, treatment = NULL, subset = NULL,
                  co_occurrence_table = NULL)

No_table = co_occurrence_network(phyloseq_obj, treatment = NULL, subset = NULL,
                                 co_occurrence_table = NULL,
                                 layout = my_layout,
                                 classification = "Family",
                                 node_colors = 'default', cluster = FALSE,
                                 cluster_colors = 'default', buffer = 0.5)

Rho_0.6 = co_occurrence(phyloseq_obj, rho = 0.6, p = 0.05, cores = 0)

With_table = co_occurrence_network(phyloseq_obj, treatment = NULL, subset = NULL,
                                   co_occurrence_table = Rho_0.6,
                                   layout = my_layout,
                                   classification = "Family",
                                   node_colors = 'default', cluster = FALSE,
                                   cluster_colors = 'default', buffer = 0.5)

ggarrange(No_table, With_table, legend = "none", ncol = 2,
          labels = c("No Table", "Rho = 0.6"))
```

![image](https://user-images.githubusercontent.com/12939587/192058205-eb2f049c-a493-4145-940e-35a2e8aaded8.png)


Please let me know if this answers your question, or if there is anything else that I can help with!

Schuyler

**Comment by PMilletich** [comment]
Just to make sure I understand, so it'll have the same edges/connections, but just a different visual layout? 

I want to do a little bit of an unorthodox method, where I have a big difference in my number of cases to controls (70 vs 1700). To mitigate this, for my past analysis I've been doing 100 iterations of controls and finding what "sticks" a majority of the time (>50 iterations). For this analysis, I was thinking about making 100 co-occurrence tables, and seeing what correlations last throughout the different control cohorts. So it ultimately doesn't matter if the network visuals are different, since I'll be mainly looking at the table. And then _maybe_ I can figure out how to make a master network? 

Does that make sense?

**Comment by schuyler-smith** [comment]
Correct, both methods of calling the network are creating identical graphs. The layout generated by igraph, which is the underlying graph package I used to generate these, is 'psuedo-random'. You could run the exact same command x number of times and it will generate y number of layouts. So, it is possible to create the same layout by chance, but it's certainly not reliable. However, even though they might be visually different, they will have the same edges and nodes.

I think I follow what you are proposing. I am not entirely convinced it's what you want to do though. Take this just as a conversation of ideas though, I haven't given it the thought it requires. I think you want to do the correlations on the entire set of controls all at once. Unless there is particular groups within the controls, then do those as control groups. I would do the entire set together, and then maybe the `phylosmith::permute_rho()` to try to identify significant co-occurrence. Also, with such a large number of samples, I'd recommend prevalence filtering to try to mitigate false-positives. Only looking at taxa that occur in at least some number of the total samples. You can do this pretty easily with `taxa_filter()`, which allows for filtering based on a proportion of samples the taxa appear in. That will cut down the runtime, and the number of false-positives. Without knowing more about your specific question in your research, this is my advice, but as I said, it likely requires more thought than I have given it.
