### ISSUE TITLE
Recommend R version for dependencies

### ISSUE THREAD

**Issue by emmalink1** [schuyler-smith/phylosmith#24]
Hi! This package seems really helpful, and I am especially excited to use the common_taxa function. However I'm having some issues installing dependencies in R 4.1.0 - 'sf' and a few other packages don't seem to be available. I am happy to install an earlier version of R to get this package and dependencies running quickly for my use- can you recommend a version? I've tried 4.0.2  and run into similar issues. Thanks!

**Comment by schuyler-smith** [comment]
Hi Emma. The most recent iteration that I pushed was built with R 4.2.1, so your version should work fine. It gives me the impression that it's a dependency issue. Are you using Windows or a Unix system?
