### ISSUE TITLE
Plotting functions fail when table contains only one taxon at level specified by "classification" parameter

### ISSUE THREAD

**Issue by jcmcnch** [schuyler-smith/phylosmith#25]
Hi Schuyler,

Thanks so much for sharing `phylosmith` with the community - I've found it to be quite helpful so far. While trying it out on my data, I came across something that is either a bug or a feature request, couldn't tell which.

In any case, I have three different time-series datasets that I need to plot side-by-side to see how the resulting data compares. I want to use `phylosmith` because line plots would be quite useful to visualize how relative abundances derived from 3 different molecular methods compare with one another across time. However, `phylosmith`'s plotting functions are failing in cases where the data input only contains a single taxon at the level specified in the `classification` parameter.

For example, I have an 18S-only dataset (`Wulf`) that I'm trying to plot. At the domain level, the command below will fail, because everything is in the "Eukaryota" Domain. 

For example, running:

`abundance_lines(Wulf, classification = 'Domain', relative_abundance = TRUE, treatment = "Sample_type", sample_labels = sample_data(Wulf)$date)`

...results in the following error:

`Error in access(object, "otu_table", errorIfNULL) : 
  otu_table slot is empty.`

It also fails with the same error if I subset to a single domain, i.e. 

```
Wulf_subset <- subset_taxa(Wulf, Phylum=="p__Diatomea")
abundance_lines(Wulf_subset, classification = 'Class', relative_abundance = TRUE, treatment = "Sample_type", sample_labels = sample_data(Wulf)$date)
```

If this is the desired behaviour, it might be nice to provide a more clear error message in this case, because it currently doesn't really tell you what the problem is and it took me a couple of hours to troubleshoot (at least I understand `R` and my code much better now haha). One reason why I found this confusing is that `phyloseq` doesn't display the same behaviour. For example, if I run `plot_bar(Wulf, "date", "Abundance", "Domain")` on the same object, it'll generate a working (albeit uninformative) barplot.

While I could get around this error by plotting only 2 or more taxa at a time, I think it would be nice if it were possible to plot only a single taxon on a plot. For example, as in the second plotting command, I might want to subset all three datasets to "p__Diatomea" and see how each molecular method compares in terms of relative abundance to one another. Do they peak at the same time? Are the relative abundances similar or very different?

Would this be something difficult to implement in your code? Or is there a simple way to hack around this issue to generate the type of plots I'm thinking of?

Thanks a lot for your time and consideration.

Best,
Jesse

**Comment by schuyler-smith** [comment]
Hi Jesse, thanks for opening this issue! This error is actually caused by an unnecessary step that I added where I used my `congolomerate_taxa` function to combine OTUs at the level given to `classification`. I could have just used `stat_summary` from ggplot and achieved, functionally, the same thing. I'll need to look at that function.. but I just pushed an update where I think `abundance_lines` should produce what you expect now. Please let me know if that is not the case and I will dig deeper to fix it! But, based on what you described, I think this was the fix.

Please let me know how it goes! I greatly appreciate your feedback.

Schuyler

**Comment by jcmcnch** [comment]
Hi Schuyler,

Thanks for the quick reply!

I did:

```
devtools::install_github('schuyler-smith/phylosmith')
detach("package:phylosmith", unload=TRUE)
```

When I reran my plotting code, I now get the expected behaviour. The error  from before is gone when I have only one taxon. Thanks!

However, it seems like your changes have introduced another problem... For some reason, there's an extra line on the plot (see image attached). It looks like it has multiple data points at each time point in my lineplot. Full code posted at the bottom in case you need to take a look.

Do you know why this might be?

Thanks,
Jesse

![extra-lines](https://user-images.githubusercontent.com/5956604/224583678-2b837cce-2d3c-46f7-b995-01c7e7dedfa5.png)

```
library(phyloseq)
library(tidyverse)
library(phylosmith)
library(gridExtra)
#import files from biom, which works now
MG <- import_biom("output-MG-combined-OTU-table/RAS_WGC_2016-2017.PacBio.merged.biom")
colnames(tax_table(MG)) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species")
Parada <- import_biom("input-tag-ASV-tables/221129-1417_FRAM-Parada_2.0-fold-18S-correction_normalized_sequence_counts.biom")
#note the taxonomy is different here because of PR2 having 8 levels
colnames(tax_table(Parada)) <- c("Domain", "Phylum", "Class", "Order", "Family", "Genus", "Species","Subspecies")
Wulf <- import_biom("input-tag-ASV-tables/230307-2053.FRAM-Wulf.18S.all-18S-seqs.with-PR2-tax.biom")
colnames(tax_table(Wulf)) <- c("Kingdom", "Supergroup", "Division", "Class", "Order", "Family", "Genus", "Species", "Subspecies")

#next import sample data
MGmeta <- read.delim("metadata/221110_sample_metadata.PacBio.tsv", sep = "\t", header = TRUE)
rownames(MGmeta) <- MGmeta$SampleID

ParadaMeta <- read.delim("metadata/221110_sample_metadata.Parada.tsv", sep = "\t", header = TRUE)
rownames(ParadaMeta) <- ParadaMeta$SampleID

WulfMeta <- read.delim("metadata/221110_sample_metadata.Wulf.tsv", sep = "\t", header = TRUE)
rownames(WulfMeta) <- WulfMeta$SampleID

#and delete the first column because it is now redundant
MGmeta <- MGmeta %>% 
  select(-SampleID)
ParadaMeta <- ParadaMeta %>% 
  select(-SampleID)
WulfMeta <- WulfMeta %>% 
  select(-SampleID)

#import into phyloseq object, then merge
MGmeta <- sample_data(MGmeta)
ParadaMeta <- sample_data(ParadaMeta)
MG <- merge_phyloseq(MG, MGmeta)
Parada <-merge_phyloseq(Parada, ParadaMeta)
WulfMeta <- sample_data(WulfMeta)
Wulf <- merge_phyloseq(Wulf, WulfMeta)

#manually set sample order by date
MG <- set_sample_order(MG, c('RAS_WSC_09_2016_1', 'RAS_WSC_10_2016', 'RAS_WSC_11_2016', 'RAS_WSC_12_2016_1', 'RAS_WSC_03_2017_2', 'RAS_WSC_05_2017_1', 'RAS_WSC_06_2017_1', 'RAS_WSC_07_2017_1', 'RAS_WSC_07_2017_2', 'RAS_WSC_07_2017_3'))

#no need to set by date since ordered in metadata. Couldn't get order function to work for some unknown reason. Probably to do with the smaller number of samples.
Parada <- subset_samples(Parada, Sample_type=="F4")
Wulf <- subset_samples(Wulf, Sample_type=="F4")
Wulf <- set_sample_order(Wulf, c('ERR5533347','ERR5533345','ERR5533344','ERR5533343','ERR5533338','ERR5533333','ERR5533331','ERR5533329','ERR5533328','ERR5533327'))

Wulf = relative_abundance(Wulf)
Parada = relative_abundance(Parada)
MG = relative_abundance(MG)

Wulf_subset <- subset_taxa(Wulf, Class=="Bacillariophyta")
Parada_subset <- subset_taxa(Parada, Family=="Bacillariophyta_X:plas")
MG_subset <- subset_taxa(MG, Phylum=="p:Diatomea")


#then do some plotting
MGline <- abundance_lines(MG_subset, classification = 'Class', relative_abundance = FALSE, treatment = "Sample_type", sample_labels = sample_data(MG)$date) + theme(axis.text.x = element_blank()) #+ scale_y_continuous(trans = "log10")
ParadaLine <- abundance_lines(Parada_subset, classification = 'Class', relative_abundance = FALSE, treatment = "Sample_type", sample_labels = sample_data(Parada)$date) + theme(axis.text.x = element_blank()) #+ scale_y_continuous(trans = "log10")
WulfLine <- abundance_lines(Wulf_subset, classification = 'Class', relative_abundance = FALSE, treatment = "Sample_type", sample_labels = sample_data(Wulf)$date) #+ theme(axis.text.x = element_blank())
grid.arrange(MGline, ParadaLine, WulfLine, ncol=1)
```

**Comment by schuyler-smith** [comment]
Oops. Yeah, that was an oversight on my part. I think it should be fixed now if you install again. Sorry, and thanks for sticking with it! Let me know if it's working now, or if there is anything else I can fix!

**Comment by jcmcnch** [comment]
Yup, that did the trick! Much obliged! Closing issue since it's solved. Thanks again for sharing your work with others - phylosmith is a huge help and makes using R/phyloseq a lot less painful for someone like me who doesn't know R very well and allows me to concentrate more on data interpretation rather than code syntax.

**Comment by schuyler-smith** [comment]
Thank you for the kind words! That was my inspiration when I first started making it.. feedback and interest from people like yourself really renews my inspiration to go back and revise/update the package because I have sort of neglected it the past couple years! Feel free to reach out with any other suggestions or things that don't work or don't work as expected!
