### ISSUE TITLE
Network analysis data question

### ISSUE THREAD

**Issue by TomasaSbaffi** [schuyler-smith/phylosmith#26]
Hello,

I am using your very nice package to run microbiome analysis and I am really liking it!
I have one (maybe naive) question about the `co_occurrence_network` function and the cluster =TRUE option, which I understand derived form `cluster_fast_greedy {igraph}`.
Is there a way to gather information about the modules generated?  Like, degree, eccentricity, centrality. I could not find such information in the outputs of the functions specified in the tutorial at https://schuyler-smith.github.io/phylosmith/networks.html.
If there is no way to derive such info, would you suggest a way to find them? thanks a lot!

**Comment by schuyler-smith** [comment]
Hi Tomasa! Thank you so much for your kind words! Sorry for the delayed response, we had a holiday weekend here.

I don't do any of the community metric calculations within the functions (though this is certainly something I am interested to build upon when I have time). If you want just the igraph object, you can use the `network_ps` function. The module membership information can then be found using `igraph::components()`, but, if I recall, you don't need to extract them for igraph to find them with its functions for community analysis. The network generated should be the same as the one you get with the `co_occurrence_network` function. Once you generate the network, igraph has a suite of functions to get the neighborhood, centrality, etc.

Does this help at all?

Schuyler

**Comment by TomasaSbaffi** [comment]
Hello!
thanks actually for your prompt answer, yes it helps a lot! I was going in that direction and I take the chance for a further question. For my network I use the "Genus" level to perform the network and the "Phylum" for classification (and therefore legend), is there a way to print in the plot all genus names or a selection of those? I find that with the `nodes_of_interest =` I can only specify the classification names (e.g. Phyla).

thanks again.

**Comment by schuyler-smith** [comment]
If the phyloseq object you are using has Genus level data, it should be able to find taxa at that level for the `nodes_of_interest`. If it is giving you an error, would you mind copying it here please? I did find a mistake that I made, but I want to make sure it's the same one that you are experiencing!
