### ISSUE TITLE
Error in taxa_abundance_bars() function

### ISSUE THREAD

**Issue by annasoli** [schuyler-smith/phylosmith#28]
Hello,

Very useful and friendly-user package. Thanks.

I am receiving the following error message:

```
Error in taxa_abundance_bars(phseq_obj_norm, treatment = "group", classification = "Species",  : 
  object '"Species"' not found
```

Used same object in another function - abundance_lines - without any problem.

Can you help?

**Comment by schuyler-smith** [comment]
Hi Ana,

Thanks for you note! I am not immediately certain what is causing this error. As a "sanity-check", is the column name in the taxa table "Species" or "species", and secondly does it also send the equivalent error at other taxonomy levels? 

If neither of these, then it's definitely a bug in my code, and I will figure it out!

Schuyler

**Comment by annasoli** [comment]
> Hi Ana,
> 
> Thanks for you note! I am not immediately certain what is causing this error. As a "sanity-check", is the column name in the taxa table "Species" or "species", and secondly does it also send the equivalent error at other taxonomy levels?
> 
> If neither of these, then it's definitely a bug in my code, and I will figure it out!
> 
> Schuyler

Hi Schuyler,

I appreciate your prompt response!
I checked. The names are correct and I also tried with Phylum and Genus. Same message.
It is weird how it appears to be looking for an 'object'. I don't know if it gives you any hint about the problem. I am trying to give a look at the source code, but I am not that R skilled. If I am able to identify something before you reach me back, I will let you know.

Thanks,

Ana

**Comment by annasoli** [comment]
Here is a funny thing.

In my first attempts, I was in Windows OS.  I tried to use 'mean' as value for the transformation parameter (it is one of the possibilities according to the R documentation). Then I received a message saying:

```
Error in value[[3L]](cond) : 
  Invalid argument 'mean' given to 'transformation'. 
  Valid arguments are: 'none', 'relative_abundance', 'log', 'log10', 'log1p', 'log2', 'asn', 'atanh', 'boxcox', 'exp', 'identity', 'logit', 'probability', 'probit', 'reciprocal', 'reverse', 'sqrt
```

I changed it to 'relative_abundance'. And then I started to receive the error that motivate this post.

Today, I am in a MacOS. And to my surprise, I am getting a different error:

```
Error in aes_string(x = classification, y = abundance, fill = treatment_name) : 
  object 'abundance' not found
```

And the error reproduces with other values to transformation, but not all. It works only with none, log, and log10.

Any thoughts?

**Comment by schuyler-smith** [comment]
Hi Ana,

Sorry, I spent the morning fighting with Xcode on MacOS to test this. I changed the way that arguments were checked in the last version i had pushed (trying be be more clever in handling them), but I made a mistake for the transformation's acceptable arguments. It should accept "mean" as expected now. If you have different versions of the package installed, that may be why the error was different on one than the other. I also made a change that should address the issue with handling the transformations within the `taxa_abundance_bars` function, that i believe was causing your original error. I was able to reproduce it and I think the current version corrected it. It did in the couple of tests i ran with `GlobalPatterns` anyways.

Try installing again with the version that I just pushed, and please let me know if the error persists.

Thanks for following up! I can appreciate that this might be annoying for you, but I greatly appreciate you helping me with this!!

Schuyler

**Comment by annasoli** [comment]
I am pretty sure the versions were the same. It was a one-day interval between the installations.

I tested it on Mac. It is working fine now. I will test it on Windows when I get home and will let you know.

Thank you for the good work and support!

Ana
