### ISSUE TITLE
set_sample_order doesn't seem to change anything

### ISSUE THREAD

**Issue by McAllister-NOAA** [schuyler-smith/phylosmith#6]
Hi!

I have a phyloseq object and am making figures that I would like the samples to be displayed in a particular order (i.e. the order they are in the table on import rather than alphabetical).

I have tried importing a list of samples in the order I want them:
```
sample_order <- as.list(read.delim("sample_order.txt", header=FALSE, stringsAsFactors=FALSE))
```

Then attempted to reorder the phyloseq object in a few ways:

```
phylo1 <- set_sample_order(phylo1, sample_order$V1)

phylo1 <- set_sample_order(phylo1, c("Samp1", "Samp2", "Samp4", "Samp5", "Samp3"))
#Just spelling it out!
```

Neither has any error, nor affect on the ggplot output from plot_bar(). Am I doing something wrong? 

The wiki says that set_sample_order supports a vector of samples in a particular order, however the only example is for sorting on metadata (not what I'm looking for).

Thanks!!

**Comment by schuyler-smith** [comment]
Sorry for a delayed response, I am not getting notifications for some reason. 

Thank you for pointing this out. You are 100% correct. Looking at the code, I wrote the check for the vector of sample names, but then never added the process. Should be a quick fix. Hopefully it will still be useful for you it I am not too late

**Comment by schuyler-smith** [comment]
I think it should work as expected now. If you are still interested. Again, sorry for the delayed response.

**Comment by McAllister-NOAA** [comment]
I'll try it out! Thanks!
