### ISSUE TITLE
Which distance is being used in nmds, pcoa and t-SNE?

### ISSUE THREAD

**Issue by FilipeMatteoli** [schuyler-smith/phylosmith#7]
Hello, thanks for the package. I am struggling trying to find out which distance the package is using in clustering analysis? Usually, we need to specify the distance, but phylosmith has no option for this, so what is being calculated under the hood?

**Comment by schuyler-smith** [comment]
Hi! Sorry, I didn't get a notification for this message in my e-mail.. and I'm not as good as I should be about checking github notifications.. 

This is a very good question. I overlooked adding the option to change the distance method. I have it written to used the Bray-Curtis distance, I should have at least wrote that in the vignette. I will add an argument to change the distance method for these functions this week!

Thanks so much!

**Comment by schuyler-smith** [comment]
@FilipeMatteoli I just pushed an updated version with a 'method' argument for each of them. By default it uses Bray-Curtis distance ('bray'), but can now take any of “euclidian”, “manhattan”, “canberra”, “bray”, “kulczynski”, “gower”, “morisita”, “horn”, “mountford”, “jaccard”, “raup”, “binomial”, “chao”, “altGower”, “cao”, “mahalanobis”, “clark”

Please let me know if there is any other feedback on this!

**Comment by FilipeMatteoli** [comment]
Hello @schuyler-smith great news I will try it soon! I always enjoy testing how different metrics affect the clustering as this can reveal hidden patterns. Thanks for this.
