### ISSUE TITLE
Legend of Genera not showing 

### ISSUE THREAD

**Issue by rogarcia1992** [schuyler-smith/phylosmith#8]
Hi,

When I try to save a plot generated using the function co_occurrence_network() as a PDF, the Genera legend is not showing. Any suggestions? Thanks!

**Comment by schuyler-smith** [comment]
Again, sorry for the late reply. I think this is likely a scaling issue through ggplot2, but I can't be certain. I would try using ggplot attribute to move the legend closer or inside the plot and see if it helps at all.
