### ISSUE TITLE
estimating separate networks according to a condition, such as a treatment

### ISSUE THREAD

**Issue by rogarcia1992** [schuyler-smith/phylosmith#9]
Hi,

Is there a way to investigate into how networks change with respect to covariates, similar to how MDine does? 

Thanks!

**Comment by schuyler-smith** [comment]
Hi, sorry that I hadn't replied to this. For some reason I am not getting e-mail notifications of issues reports, I'll need to figure out why..

I am not familiar with MDine, so the short answer is no. I'll have too look into what it is and see how it might be implemented! I am assuming it gives measurements on network composition based on which variable the network is built from?
